# PARTE 2: FUNDAMENTOS DE PROGRAMACIÓN

## PARTE 2.1: OPERACIONES ARITMÉTICAS BÁSICAS

#### OPERACIONES

In [ ]:
#SUMA
print(1+4)
print(3+7)      

In [ ]:
#RESTA
print(1-4)
print(3-7)

In [ ]:
#MULTIPLICACIÓN
print(1*-4)
print(3*7)

In [ ]:
#DIVISIÓN 
#Este tipo de división si genera residuo
print(1/4)
print(3/7)
print(8/3)
print(8/6)

In [ ]:
#MÓDULO - RESIDUO DE UNA DIVISIÓN
#El uso del módulo es una excelente forma para poder obtener el residuo entero de una divisón
print(7%2)
print(8%2)
print(10%4)
print(8%6)

#Con el siguiente ejemplo pretenderemos ver el uso para ver cómo se comporta

numero_1 = int(input('Ingresa un número:' ))
numero_2 = int(input('Ingresa otro número: '))

if numero_1%2 == 0:
    print('El primer número es impar')
if numero_2%2 != 0:
    print('El segundo número es impar')


In [ ]:
#POTENCIA
print(7**2)


#Importamos el módulo de math para realizar operaciones matemáticas complejas
import math
print(math.pow(7,2))


#El método math.pow, pasamos el número y las veces que lo queremos elevar
print(math.pow(3,3))


numero1 = 9
numero2 = 8

numero_potencia = (math.pow(numero1, numero2))
print(numero_potencia)

print(9**8)
#Se puede observar que ambos métodos funcionan de manera igual, de tal manera que cualquier forma es válida, ya sea con el doble ** o 

In [ ]:
#RAÍZ CUADRADA

# Raíz cuadrada mediante el método aritmético
print(9**(1/2))

# Uso de la raiz cuadrada mediante la función math.sqrt, seguido del parámetro a obtener
print(math.sqrt(9))
print(math.sqrt(52))
print(math.sqrt(894))
print(math.sqrt(854987))

# Usando el método extend
import math

# Creamos una lista vacía
lista = []

# Iteramos en un rango desde el 1 hasta el 10 para obtener valores
for n in range(1, 10):
    # Añadimos los números a la lista vacía con el método extend. a la lista
    lista.extend(range(1, 10, n))
# Iteramos en los elemntos de la lista para obtener su raíz cuadrada
for n in lista:
    print('la raiz cuadrada de cada numero es: ', math.sqrt(n))

print(lista)


In [ ]:
#VALOR ABSOLUTO

#El valor absoluto de un número es el mismo número sin tomar en cuenta su signo para ello vasta con llamar al módulo abs, seguido del número que deseamos utilizar 
print(abs(-200))
print(abs(200))

print(abs(-354))

#### REDONDEO

In [ ]:
#REDONDEO CLÁSICO
print(round(10.51))
print(round(10.6))
print(round(89.46))
n1 = 89.4
n2 = 89.56
n3 = (round(n1 * n2)) 
res = f'al multiplicar los números {n1} y {n2} y aplicar el redonde clasico obtenemos lo siguiente: {n3} y sin el redondeo obtendriamos el siguiente resultado:', (n1*n2)
print(res)


#Siempre que el redondeo sea menor a .5 se aplica el redondeo haca abajo y siempre que este sea mayor a .5 siempre será el redondeo hacia arriba

In [ ]:
#REDONDEO HACIA

# El módulo math, también incluye redondeo menor el cual siempre 
# devolverá un entero sin importar cuántas decimales tenga
print(math.floor(1.2564578))
print(math.floor(1.111121121))
print(math.floor(1.49))
print(math.floor(1.99))
print(math.floor(11.999999))
print(math.floor(11.1))

In [ ]:
#REDONDEO HACIA ARRIBA

# De la misma manera, el método ceil, de la librería math, hará todo lo contrario
# Mediante este método el redondeo siempre será el entero más proximo hacia arriba
print(math.ceil(11.999999))
print(math.ceil(1.25254478))
print(math.ceil(.245512))
print(math.ceil(11.1))

In [1]:
#TRUNCAMIENTO
import math
# Esta métodos no redonde ni de forma clásica, ni hacia arriba ni hacia abajo.
# Solo permite obtener el valor del entero excluyendo cualquier parte deciaml.
print(math.trunc(11.99999))
print(math.trunc(23.56))
print(math.trunc(22.99999))
print(math.trunc(11.1))

11
23
22
11


#### CONSTANTES MATEMÁTICAS

In [ ]:
math.pi

# El m+odulo math también incluye constantes matemáticas como el método math.pi
# El cual, nos permite utilizarlo dentro de nuestro código como si fuera un valor más
a = None
b = 23
c = math.pi

a = (math.pi*b)**2
print(f'El area de este círculo es: {a}')

In [ ]:
math.e
# También incluye el número do euler para cuando sea necesario tengamos más acceso
# y manera inmediata podamos utilizar esta función.


## PARTE 2.2: MANEJO DE CADENAS

In [ ]:
#IMPRIMIR UN MENSAJE EN CONSOLA

# En Python cualquier caracter es considerado un string.
# Este tipo de dato siempre se debe declarar con comillas simples ('') dobles (" ")
# o triples.
print("HOLA MUNDO")
print('HOLA MUNDO')


# Cuando tengamos la necesidad de utilizar las comillas para resaltar un texto, 
# Palabra frase u oración será necesario jugar con su uso de la siguiente manera:
NOMBRE = "Eduardo"

# En el siguiente codigo la  el string lo declaramos con comillas dobles (" ")
# Pero resaltamos la palabra con comillas simples (' ')
# De esta manera lo que se imprime en pantalla es las comillas simples (' ')
print("'HOLA'",NOMBRE, "." " Cómo has estado? ")


print("HOLA","NOMBRE") #TEXTO "NOMBRE"

In [ ]:
#IMPRIMIR UN MENSAJE CON COMILLAS
#HOLA ME DICEN "BENJI"
print("HOLA ME DICEN 'BENJI' ")
print('HOLA ME DICEN "BENJI" ')

In [ ]:
#TABULACIONES

# En Python, hay instrucciones reservada que no se ejecutan como código directo
# Ejemplo de ello es la setencia \t Esta instrucción se interpreta como "genera una tabulación"
print("HOLA ME DICEN \t'Lalo' ")
print("Nombre: \t", "Eduardo" )

In [ ]:
#SALTO DE LÍNEA Y TABULACIÓN
print("Hola, me dicen \n'Lalo.'", "Mi nombre es: \t Eduardo \n y mi \n apellido es:\t Moreno" ) 

In [ ]:
#TEXTO SIN EJECUTAR COMANDOS

# El método raw (r) no intepreta ningún tipo de instrucción
# y devuelve todo como texto crudo sin interpretar ningún tipo de instrucción
print(r"HOLA ME DICEN \n\t'BENJI' ") #raw

# Salida sin raw
print("La vida del mundo\nes una forma de vivir\t y vivir es vivir")


# Salida con raw
print(r"La vida del mundo \n es una forma de vivir \t y vivir es vivir")

In [ ]:
#MOSTRAR VARIAS LÍNEAS

# El uso de las tres comillas (""" """) no solo sirve para que un texto sea exluído del código
# Tienen una función al momento de imprimirse y este es, que nos permite imprimir varias
# Líneas de código donde podemos ubicar el texto en cualquier parte del mensaje a imprimir
print("""hola
estoy
estudiando
python""")

menu = """
Elige una opción del menú:

            opción 1: Sumar
            opción 2: Restar
            opción 3: Multiplicar
            opción 4: Dividir
"""
print(menu)

In [ ]:
#SUMA DE CADENAS
C1 = "HOLA "
C2 = "MUNDO"
print(C1+C2)
print(C1,C2)

In [ ]:
#MULTIPLICACIÓN DE CADENAS
C1 = "ABC"
print(C1*3)
print(C1+C1+C1)

In [ ]:
#ÍNDICES DE CADENAS
#Siempre se accede a un índice de un string mediante los corchetes
#Ya que un string es en sí mismo una lista de elementos concatenados

C1 = "Eduardo Leon"
print(C1[0])
print(C1[5])

print(C1[8])
print(C1[-1])
print(C1[-6])

In [ ]:
#SLICING DE CADENAS

#El slicing de cadenas (porción de algo) siempre se invoca con los dos puntos
# es decir " desde aquí hasta aca (:-1)" esto se leería como desde el inciio
#hasta el penúltimo

C3= "Ejemplo de porción"
    # E j e m p l o     d e      p   o   r   c   i    o  n
    # 0 1 2 3 4 5 6  7  8 9  10  11  12  13  14  15  16  17
print(C3[:4])#Considera que esto se lee como desde el "cero hasta el 3"

print(C3[4:7])#Considera que esto se lee como "desde la posición 4 hasta la 6 "

print(C3[8:10])#Considera que esto se lee como "desde la posición 8 hasta la 9 "

print(C3[11:])#Considera que esto se lee como "desde la posición 11 hasta el final "


print(C3[0:18])#Considera que esto se lee como "desde la posición 0 hasta la 17 "




In [ ]:
#NO SE PUEDE MODIFICAR MEDIANTE SLICING O ÍNDICES
C1 = "Eduardo León"
C1[0] = "X"
"""
Si intenatmos modificar un elemnto a través de su índice resiviremos el siguiente error:
TypeError                                 Traceback (most recent call last)
Cell In[49], line 3
    1 #NO SE PUEDE MODIFICAR MEDIANTE SLICING O ÍNDICES
    2 C1 = "Eduardo León"
----> 3 C1[0] = "X"

TypeError: 'str' object does not support item assignment
"""

In [ ]:
#LONGITUD DE UNA CADENA
#La función len() devuelve la cantidad de elemntos que contiene una variable
C4 = "Eduardo Leon"
print(len(C4))

lista_01 = ['Juan', 'Antonio','Ramiro','Uvaldo']

print((f'La lista contiene {len(lista_01)} elementos'))
print(f'El elemento 0 de la lista contiene {len(lista_01[0])} caracteres')
print((f'El elemento 1 de la lista contiene {len(lista_01[1])} caracteres'))
print(f'El elemento 2 de la lista contiene {len(lista_01[2])} caracteres')
print(f'El elemento 3 de la lista contiene {len(lista_01[3])} caracteres')





In [ ]:
#FUNCIÓN UPPER --> VUELVE A MAYÚSCULAS LA CADENA

#La función upper() nos permite manipular los str de tal manera que cada uno de los caracteres
#cambiará de minúsculas a mayúsculas
texto = 'Eduardo Leon'# Si hay mayúsculas se excluyen de manera automática
print(texto.upper())

texto_2 = 'mi mamá me mima'
print(texto_2.upper())
print(texto_2.isupper())

if (texto_2 and texto).isupper() == True:
    print('La cadenas de texto están en minúsculas')
else:
    print('Ambas cadenas de texto están en mayúsculas')

In [ ]:
#FUNCIÓN LOWER --> VUELVE A MINÚSCULAS LA CADENA
texto_3 = 'EDUARDO LEON'
texto_4 = 'MI MAMÁ ME MIMA'
print(texto_3.lower())
print(texto_4.lower())

#Ejercicio 1
if (texto_3 and texto_3).islower() == True:
    print('Ambas cadenas de texto están en minúsculas')
else:
    print('Las cadenas de texto están en mayúsculas')

#Ejercicio 2
texto_5 = 'Mi mamá me Mima'
texto_6 = 'La vida es bella'
print()
if (texto_5 and texto_5).islower == True:
    print('Ambas cadenas de texto están en minúsculas')
else:
    print('O alguna cadena de texto no está en minúsculas o contienen \nalgún caracter en mayúsculas')

print()
#Ejercicio 3

print(texto_3,'\n',texto_4)
if (texto_3 and texto_4).islower()== False:
    print(texto_3.lower(),'\n',texto_4.lower())


In [ ]:
#CAPITALIZE --> VUELVE MAYÚSCULA SOLO EL PRIMER CARACTER
texto = 'LA vacuna DEL COVID-19'
print(texto.capitalize())

In [ ]:
#TITLE --> VUELVE MAYÚSCULA SOLO EL PRIMER CARACTER DE CADA PALABRA
#Convierte cada str en mayúsculas de una frase para volverla un título

#Declaramos variables
texto_7 = 'LA vacuna DEL COVID-19'
print(texto_7)
texto_8 = 'la vida es bella'
print(texto_8)

#Convertimos variables a títulos
texto_7 = texto_7.title()
texto_8 = texto_8.title()

#Imprimimos variables en forma de título
print(texto_7)
print(texto_8)

#Evaluamos sin son títulos cada variable
print(texto_7.istitle())
print(texto_8.istitle())

In [2]:
#COUNT --> DEVUELVE LA CANTIDAD DE VECES QUE APARECE UNA CADENA EN OTRA

#La Función count hace un recuento de búsqueda sobre cuántas veces aparece un elemnto
#dentro de una variable
texto_9 = "HOLA MUNDO MUNDO MUNDO"
print(texto_9.count("MUNDO"))
print(texto_9.count("mundo"))

nombre = 'Eduardo Omar Moreno León'

print(nombre.count('Eduardo'))
print(nombre.count('Omar'))

numbers = [1,1,2,3,4,5,6,7,8,9]
print(numbers.count(1))

#Al intentar ejecutar el método .count() dentro de un diccionario tendremos el siguiente error:
diccionary = {
    'clave': 'valor',
    'nombre':'Eduardo',
    'apellido': 'Moreno'
    }

print(diccionary.count('Eduardo'))
"""AttributeError                            Traceback (most recent call last)
Cell In[5], line 23
    15 print(numbers.count(1))
    17 diccionary = {
    18     'clave': 'valor',
    19     'nombre':'Eduardo',
    20     'apellido': 'Moreno'
    21     }
---> 23 print(diccionary.count('Eduardo'))

AttributeError: 'dict' object has no attribute 'count'"""

#El cual nos indica que dicho objeto no posee tal atributo

3
0
1
1
2


AttributeError: 'dict' object has no attribute 'count'

In [3]:
#FIND --> TE DICE LA PRIMERA POSICIÓN DESDE LA IZQUIERDA EN EL QUE SE ENCUENTRA UN TEXTO
texto_10 = "HOLA MUNDO MUNDO MUNDO"
print(texto_10.find("MUNDO"))
print(texto_10.find("mundo"))

nombre = 'Eduardo Omar Moreno Leon'
print(nombre.find('Eduardo'))#Indica que 'Eduardo'empieza en el índice '0'
print(nombre.find('Omar'))#Indica que el elemnto empieza en el índice 8
print(nombre.find('Moreno'))#Indica que el elemento empieza en el índice 13
print(nombre.find('Leon'))# Indica que el elemnto empieza en el índice 20

5
-1
0
8
13
20


In [7]:
#RFIND --> TE DICE LA PRIMERA POSICIÓN DESDE LA DERECHA EN EL QUE SE ENCUENTRA UN TEXTO
texto_11 = "Eduardo Omar Moreno Leon"
print(texto_11.rfind("MUNDO"))#Cuando no se encuentra el índice del elemnto devuelve -1
print(texto_11.rfind("mundo"))#Cuando no se encuentra el índice del elemnto devuelve -1
print(nombre.rfind('Eduardo'))
print(nombre.rfind('Omar'))
print(nombre.rfind('Moreno'))
print(nombre.rfind('Leon'))
texto_12 = 'Eduardo'
print(texto_12.rfind('d'))#Aquí se leería "dime desde la derecha hacia la izquierda, dónde aparece la letra 'd'""

-1
-1
0
8
13
20
5


In [ ]:
#ISDIGIT --> True (CUANDO TODOS LOS CARACTERES SON CIFRAS)

#Esta función nos indica si todos los elemntos son dígitos en la variable
print("45245".isdigit())
print("45245.9".isdigit())#Aquí nos devuelve False por el (.)
print("45245e".isdigit())
print("3.14159263".isdigit())

#Se debe de colocar el elemento a consultar con comillas (' ' o "  " o """"  """ )
print("""3256478""".isdigit())

In [ ]:
#ISALNUM --> True (CUANDO TODOS LOS CARACTERES SON ALFANUMÉRICOS)

print("dfasdfQQQQQQQa3424".isalnum())
print("abcd5".isalnum())
print("12345".isalnum())
print("12345.6".isalnum())

nombre_1 = 'Eduardo1'#Contiene números y letras (True)
nombre_2 = 'Eduardo2.'#Contiene un punto devuelve (False)
nombre_3 = 'Eduardo'#Contiene caracteres devuelve (True)
print(nombre_1.isalnum())
print(nombre_2.isalnum())
print(nombre_3.isalnum())


In [ ]:
#ISALPHA --> True (CUANDO TODOS LOS CARACTERES SON LETRAS)
nombre_4 = 'Eduardo'
nombre_5 = 'Omar'
nombre_6 = 'Moreno'
nombre_7 = 'León'#Los acentos también son considerados letras
nombre_8 ='djskjd,.;_:'#Solo los acentos los considera letras
print(nombre_4.isalpha())
print(nombre_5.isalpha())
print(nombre_6.isalpha())
print(nombre_7.isalpha())
print(nombre_8.isalpha())
print()
print("hola".isalpha())
print("Hola".isalpha())
print("Hola R2D2".isalpha())
print("Hola, soy Gokú".isalpha())
print("Hola soy Gokú".isalpha())
print("HolasoyGokú".isalpha())

In [ ]:
#ISLOWER --> True (CUANDO TODOS LOS CARACTERES SON LETRAS MINÚSCULAS)
nombre == nombre
if nombre.islower() == False:
    print(nombre)#Como la variable nombre no está en minúsculas nos devuelve su valor
                #y comprobamos que tiene caracteres en mayúsculas

print("hola".islower())
print("hola, soy gokú".islower())
print('hola soy gokú'.title().islower())#Cambiamos el texto a Título y después preguntamos
                                        #Si está en minúsculas, como no está en minúsculas
                                        #nos devuelve False
numbers_2 = "1,2,3,4"#Convertirmos numeros a str
print(type(numbers_2))#Preguntamos que tipo de datos es
print(numbers_2.islower())#Preguntamos si están en minúsculas y determina que no son letras
                        # y que tampoco están en minúsculas


In [ ]:
#ISUPPER --> True (CUANDO TODOS LOS CARACTERES SON LETRAS MAYÚSCULAS)

nombre_9 = 'Eduardo'
print(nombre_9.isupper())#Solo la primer letra está en mayúsculas
print(nombre_9.upper().isupper())#Convertimos a mayúsculas y después evaluamos si ya
                                #se encuentra en mayúsculas a lo cual retorna True

print()
print("HOLA".isupper())
print("hola, soy gokú".isupper())
print("Hola, soy gokú".isupper())
print("1234".isupper())

In [ ]:
#ISTITLE --> True (CUANDO LA CADENA ES UN TÍTULO)

texto_12 = 'Eduardo Omar Moreno León'
print(texto_12.istitle())
print()

texto_13 = 'eduardo omar moreno león'
print(texto_13.title().istitle())
print()

print("Hola Soy Gokú".istitle())
print("HOLA SOY GOKÚ".istitle())

In [8]:
#ISSPACE --> True (CUANDO LA CADENA SOLO MUESTRA ESPACIOS)

texto_14 = ' h   o la'
print(texto_14.isspace())
print()

print("          ".isspace())
print("           .     ".isspace())

False

True
False


In [9]:
#STARSWITH --> True (SI LA CADENA EMPIEZA CON DETERMINADA CADENA)

texto_15 = 'Me llamo papita'
print(texto_15.startswith('Me'))
print(texto_15.startswith('papita'))
print(texto_15.startswith('llamo') )
print()
print("Hola Soy Gokú".startswith("Hola"))
print("Hola Soy Gokú".startswith("Gokú"))

True
False
False

True
False


In [10]:
#ENDSWITH --> True (SI LA CADENA CULMINA CON DETERMINADA CADENA)
texto_16 = 'La vida es bella'
print(texto_16.endswith('bella'))
texto_17 = 'Anita lava la tina'
print(texto_17.endswith('tina'))

print()
print("Hola Soy Gokú".endswith("Gokú"))
print("Hola Soy Gokú".endswith("Hola"))

True
True

True
False


In [21]:
#SPLIT --> TE PERMITE DIVIDIR UNA CADENA CON BASE EN ALGÚN CARACTER/CADENA
print(type("HOLA MUNDO MUNDO TIERRA 2021"))
print("HOLA MUNDO MUNDO TIERRA 2021".split(" "))#Mec corta la cadena y la devuelve en
                                                    #Forma de lista
print(type("HOLA MUNDO MUNDO TIERRA 2021"))
print("HOLA MUNDO MUNDO TIERRA 2021".split("MU"))

texto_18 = 'Eduardo Omar Moreno León'
print(texto_18.split("a"))
texto_19 = 'Prueba'
texto_19 = texto_19.split('r')#Corta donde encuentra la 'r', la omite y separa la cadena, por último la devuelve en forma de lista
print(type(texto_19))
print(texto_19)
for e in texto_19:
    print(e)#Nos devuelve solo dos elemntos 'P' y 'ueba', ya que con el método split
            #Cortamos la cadena donde estaba 'r', esta se elimina y nos devolvió ya no una cadena,
            #Sino una lista de elemntos: ('P' y 'ueba')

<class 'str'>
['HOLA', 'MUNDO', 'MUNDO', 'TIERRA', '2021']
<class 'str'>
['HOLA ', 'NDO ', 'NDO TIERRA 2021']
['Edu', 'rdo Om', 'r Moreno León']
<class 'list'>
['P', 'ueba']
P
ueba


In [148]:
#JOIN --> TE PERMITE UNIR UNA CADENA CON BASE EN ALGÚN CARACTER/CADENA
texto_19 = 'Eduardo Omar Moreno León'
print(texto_19, end=',')

print('_'.join(texto_19))
print("Eduardo Omar Moreno León \n".join("HOLA MUNDO"))
print(".XYZ.".join("HOLA MUNDO"))


Eduardo Omar Moreno León,E_d_u_a_r_d_o_ _O_m_a_r_ _M_o_r_e_n_o_ _L_e_ó_n
HEduardo Omar Moreno León 
OEduardo Omar Moreno León 
LEduardo Omar Moreno León 
AEduardo Omar Moreno León 
 Eduardo Omar Moreno León 
MEduardo Omar Moreno León 
UEduardo Omar Moreno León 
NEduardo Omar Moreno León 
DEduardo Omar Moreno León 
O
H.XYZ.O.XYZ.L.XYZ.A.XYZ. .XYZ.M.XYZ.U.XYZ.N.XYZ.D.XYZ.O


In [22]:
#STRIP --> ELIMNA ALGÚN CARACTER O CADENA DEL INICIO Y FINAL

mensaje = 'anita lava la tina       '
print(mensaje.strip(" "))


print("          HOLA MUNDO. ,               ".strip("," "." " "))
print("_________________HOLA MUNDO______________".strip("_"))

anita lava la tina
HOLA MUNDO
HOLA MUNDO


In [28]:
#REPLACE --> REEMPLAZA UNA CADENA CON OTRA
print("HOLA MUNDO".replace("O","0").replace('A', '4'))
print("HOLA MUNDO MUNDO MUNDO".replace("MUNDO","-"))
print("HOLA MUNDO MUNDO MUNDO".replace("MUNDO","-",1))#Esto se lee como "Reemplaza 'MUNDO por - solo una vez"

H0L4 MUND0
HOLA - - -
HOLA - MUNDO MUNDO


In [32]:
#ALGORITMO PARA INVERTIR UNA CADENA
cadena = 'HOLA MUNDO ESTAMOS EN EL 2021'
print(cadena[::-1])

mensaje = 'anita lava la tina'
print(mensaje[::-1])

mensaje_2 = 'mi mamá me mi mama'
print(mensaje_2[::-1])

mensaje_3 = 'Tu tienes la culpa'
print(mensaje_3[::-1])#Esto se lee como "Desde el inicio hasta el final,
                    #devuelve cada uno de los elemntos en el orden inverso"
print(mensaje_3[:3:-1])#Esto se lee como "Empieza desde el inicio, pero donde termine la
                    #posición 3, quiero que devuelvas todos los elementos en el orden inverso")

1202 LE NE SOMATSE ODNUM ALOH
anit al aval atina
amam im em ámam im
apluc al seneit uT
apluc al senei


## PARTE 2.3: TIPO DE DATO LÓGICO / BOOLEANO

In [172]:
2 == 5 #Esto se lee como 2 es igual a 5?
    #Se evalúa la condición y como 2 no es igual a 5
    #Entonces retorna False

False

#### TRUE ---> 1

In [173]:
1==1#Esto se lee como 1 es igual a 1?
    #Se evalúa la condición y como 1 es igual a 1
    #Entonces retorna True

True

In [175]:
True + 1#Esto se lee como 1 más 1
    #Se evalúa la condición y como 1 más 1 es igual a 2
    #Entonces retorna 2 como0 resultado

2

In [178]:
(1==1)*3
#Esto se ejecutaría de la siguiente manera:
    #1 es igual a 1: SI (True),
    #(True)*3, sería: 1*3 por tanto devolvería lo siguiente como resultado:
    #3

3

#### FALSE ---> 0

In [183]:
print(f'la siguiente condición es:{1==2} (falsa) ya que uno no es igual a 2')

la siguiente condición es:False (falsa) ya que uno no es igual a 2


In [186]:
print(f'La siguiente operación es {False + 4} ya que False se opera como "0"\ny se entendería como 0 + 4')

La siguiente operación es 4 ya que False se opera como "0"
y se entendería como 0 + 4


In [187]:
print(f'Aquí evaluamos la condición {(1==2)*3} como esta condición\nserá falsa retornará "0", después se multiplicará\npor 3, por lo tanto nos devolverá cero como resultado ')

Aquí evaluamos la condición 0 como esta condición
será falsa retornará "0", después se multiplicará
por 3, por lo tanto nos devolverá cero como resultado 


## PARTE 2.4: OPERADORES RELACIONALES

In [188]:
#IGUAL QUE
print(f'Esta operación evalúa si un valor es igual a otro, si es verdadera retornará True\n{6==8} caso contrario, retornará False')
print(6==6)

Esta operación evalúa si un valor es igual a otro, si es verdadera retornará True
False caso contrario, retornará False
True


In [192]:
#DIFERENTE QUE
print( f'De la misma manera el operador != (el cual se lee como es distinto de)\n{6!=8} evalúa la condición y si esta es verdadera retornará True\ncaso contrario retornará False' )
print()
print(6!=6)

De la misma manera el operador != (el cual se lee como es distinto de)
True evalúa la condición y si esta es verdadera retornará True
caso contrario retornará False

False


In [198]:
#MAYOR QUE
print( f'De la misma manera el operador >(el cual se lee, como es mayor que)\n{6>4} Evalúa si la condición es correcta,\ncaso contrario devolverá False' )
print()
print( f'Aquí tenemos un caso interesante (6>6) {6>6}\nya que se está evaluando si es mayor que, pero ambos\nson iguales, así que al no ser mayor, sino iguales devuelve False' )

De la misma manera el operador >(el cual se lee, como es mayor que)
True Evalúa si la condición es correcta,
caso contrario devolverá False

Aquí tenemos un caso interesante (6>6) False
ya que se está evaluando si es mayor que, pero ambos
son iguales, así que al no ser mayor, sino iguales devuelve False


In [ ]:
#MENOR QUE
print(6<4)
print(6<8)

In [36]:
#MAYOR IGUAL QUE
print(6>=4)
print(6>=8)
if (8>=6):
    print(f"La operación {(8>=6)} es correcta, por tanto 8>=6")

True
False
La operación True es correcta, por tanto 8>=6


In [ ]:
#MENOR IGUAL QUE
print(6<=4)
print(6<=8)

In [202]:
#COMPARACIÓN CON VARIABLES
VAR = 10 #Declaramos que VAR es igual a 10
VAR + 1 == 10 #Aquí no operamos sino preguntamos si VAR + 1 es igual a 10,
            # Por tanto, al ser incorrecto esto devolverá False

False

In [204]:
#COMPARACIÓN CON CADENAS
C1 = "HOLA"
C2 = "Hola"
C3 = "hola"

print(C1 == C2)#Evalúa que sean los mismos caracteres
print(C1 == C3)#Evalúa que sean los mismos caracteres
            # Como ninguna variable contiene los mismos caracteres retornará False

False
False


In [38]:
#OPERADORES RESUMIDOS

"""Siempre se evalúan los parénteis
y despues de ejecutarse las operaciones internas 
se evalúan los operadores lógicos"""
print((1<5) and (5<8))#"1 es menor que 5?(True), "5 es menor que 8(True)?
                    #Si ambos son True, la operación devolverá True
print(1<5<8)#De igual manera se analiza en orden secuencial "1 es menor que 5(True),"
            #"5 es menor que 8(True), si ambos son True, la operación devolverá True"

True
True


In [ ]:
print((10>5) and (5>3))
print(10>5>3)

## PARTE 2.5: OPERADORES LÓGICOS

In [ ]:
#PARA IMPORTAR IMÁGENES
from IPython.display import Image
Image(filename = "RECURSOS - CERTIFICACIÓN/TABLAS DE VERDAD.png")

#TRUE -> UNIVERSO
#FALSE -> VACÍO

#AND -> INTERSECCIÓN
#OR -> UNIÓN

In [8]:
#NEGACIÓN
print(not True)#Cambia el valor de True a False
print()

casado = 'Es casado'
print(not casado)
print()

print(not False)#Cambia el valor de False a True
print()

print(not (1==1))#La operacion es True, pero al pasarle el bool "not", nos devuelve False
print()

print(not (2==1))#La operación es False, pero al pasarle el bool "not", nos devuelve True

False

False

True

False

True


In [13]:
#CONJUNCIÓN - AND
print( (True) and (True) )#Si ambas son verdaderas, su resultado será True
print( (False) and (True) )#Como no son verdaderas su resultado será False
print()

print( (1==1) and (5>=2) )#Como al operar primero los paréntesis, ambas devuelven True
                        #Al ejecutar el operador and, el cual evalúa si ambas son verdaderas
                        #Este nos devuelve True
print()

print( (1<5) and (4>7) )#La segunda operación es False, y si una de ellas es falsa, nos
                        #La condición no se cumplirá y se retornará False

True
False

True

False


In [18]:
#DISYUNCIÓN - OR
print( (True) or (True) )#Si ambas son verdaderas, retornará True
print()

print( (False) or (False) )#Si ambas son falas, retornará False
print()

print( (1==1) or (5>=2) )#De la misma manera, siempre se empieza la evaluación por
                        #paréntesis primero, ya obtenidos los valores se operan de manera lógica
                        #En este caso, como ambas son verdaderas, nos devolverá True
print()

print( (1<0) or (4>7) )#Al evaluar cada expresión primero se obtenie que ambas son falsas
                    #y el operador "or" siempre devolverá False si ambas son falsas

True

False

True

False


## PARTE 2.6: OPERACIONES ANIDADAS

Se deben solucionar teniendo en cuenta las siguientes reglas:
* Los paréntesis
* Las operaciones matemáticas (exp >> mult >> div >> sum >> res)
* Las expresiones relacionales
* Las expresiones lógicas

In [19]:
(((1==1) and (1>=3)) * 3 + 1) > 8 / 2
#(((True) and (False)) * 3 + 1) > 8 / 2
#((False) * 3 + 1) > 8 / 2
#(0 + 1) > 8 / 2
#(1) > 8 / 2
#(1) > 4
#False

False

## PARTE 2.7: OPERACIONES DE ASIGNACIÓN

In [23]:
#ASIGNACIÓN SIMPLE
VARIABLE = 10
VARIABLE = VARIABLE + 5


print(VARIABLE)

15


In [27]:
#SUMA EN ASIGNACIÓN
VARIABLE = 10
VARIABLE += 5
VARIABLE_2 = 15
VARIABLE_2 += 5
print(VARIABLE)
print(VARIABLE_2)


15
20
15


In [28]:
#RESTA EN ASIGNACIÓN
VARIABLE = 10
VARIABLE -= 5

VARIABLE_3 = 20
VARIABLE_3 -= 5

print(VARIABLE)
print(VARIABLE_3)


5
15


In [ ]:
#MULTIPLICACIÓN EN ASIGNACIÓN
VARIABLE = 10
VARIABLE *= 5

print(VARIABLE)

In [ ]:
#DIVISIÓN EN ASIGNACIÓN
VARIABLE = 10
VARIABLE /= 5

print(VARIABLE)

In [33]:
#MÓDULO EN ASIGNACIÓN 
VARIABLE = 10
VARIABLE %= 5
VARIABLE_4 = 10.23
VARIABLE_4 %= 5
print(VARIABLE)
print(VARIABLE_4)#Devuelve el resíduo de la operación con el uso del módulo (%)


0
0.23000000000000043


In [34]:
#POTENCIA EN ASIGNACIÓN
VARIABLE = 10
VARIABLE **= 5

print(VARIABLE)

100000


## PARTE 2.8: ALEATORIOS CON RANDOM

In [37]:
import random

In [45]:
#GENERAR UN ALEATORIO DECIMAL ENTRE 0-1
random.random()#No se ingresa ningún argumento
aleatorios_1=random.random()
print(aleatorios_1)
print()

aleatorios_2=random.random()
print(aleatorios_2)


0.9149744833065437

0.013784628956555633


In [54]:
#GENERAR UN ALEATORIO DECIMAL UNIFORME(CON LA MISMA PROBABILIDAD DE SALIR) ENTRE 2 NÚMEROS
random.uniform(20,30)
""" 
La función random.uniform (20, 30)
te devuelve un número al azar entre 20 y 30.
Cualquier número entre 20 y 30 tiene la misma probabilidad de salir.
Por ejemplo, la probabilidad de que salga 25
es la misma que la de que salga 29.
Esa probabilidad es 1/10, porque hay 10 números posibles entre 20 y 30.
Si quieres saber la probabilidad de que salga un número entre 22 y 26,
por ejemplo, tienes que contar cuántos números hay entre 22 y 26.
Hay 5 números: 22, 23, 24, 25 y 26. Entonces la probabilidad es 5/10,
porque hay 5 números de los 10 posibles.
"""

' \nLa función random.uniform (20, 30)\nte devuelve un número al azar entre 20 y 30.\nCualquier número entre 20 y 30 tiene la misma probabilidad de salir.\nPor ejemplo, la probabilidad de que salga 25\nes la misma que la de que salga 29.\nEsa probabilidad es 1/10, porque hay 10 números posibles entre 20 y 30.\nSi quieres saber la probabilidad de que salga un número entre 22 y 26,\npor ejemplo, tienes que contar cuántos números hay entre 22 y 26.\nHay 5 números: 22, 23, 24, 25 y 26. Entonces la probabilidad es 5/10,\nporque hay 5 números de los 10 posibles.\n'

In [52]:
#GENERAR UN ALEATORIO ENTERO ENTRE 2 NÚMEROS
random.randrange(20,30)
random.randrange(30)

"""random.randrange (20, 30) es una función de Python que te devuelve
un número entero al azar entre 20 y 30, sin incluir el 30. Es decir,
la probabilidad de que salga cualquier número del 20 al 29 es la misma: 1/10.
Por ejemplo, la probabilidad de que salga 25 es la misma que la de que salga 28: 1/10.

Esta función es diferente de random.uniform (20, 30), que te devuelve
un número real al azar entre 20 y 30, incluyendo el 30. Es decir,
la probabilidad de que salga cualquier número entre 20 y 30 es la misma,
pero hay infinitos números posibles. Por ejemplo, la probabilidad de que salga 25
es la misma que la de que salga 28.5 o 29.9999.

Ambas funciones siguen una distribución uniforme, pero una es discreta y la otra
es continua. La distribución uniforme significa que todos los valores posibles
tienen la misma probabilidad de ocurrir. Se puede representar gráficamente con
una línea recta horizontal que indica la probabilidad constante para cada valor.
"""


'random.randrange (20, 30) es una función de Python que te devuelve\n\nun número entero al azar entre 20 y 30, sin incluir el 30. Es decir,\n\nla probabilidad de que salga cualquier número del 20 al 29 es la misma: 1/10.\n\nPor ejemplo, la probabilidad de que salga 25 es la misma que la de que salga 28: 1/10.\n\n\nEsta función es diferente de random.uniform (20, 30), que te devuelve\n\nun número real al azar entre 20 y 30, incluyendo el 30. Es decir,\n\nla probabilidad de que salga cualquier número entre 20 y 30 es la misma,\n\npero hay infinitos números posibles. Por ejemplo, la probabilidad de que salga 25\n\nes la misma que la de que salga 28.5 o 29.9999.\n\n\nAmbas funciones siguen una distribución uniforme, pero una es discreta y la otra\n\nes continua. La distribución uniforme significa que todos los valores posibles\n\ntienen la misma probabilidad de ocurrir. Se puede representar gráficamente con\n\nuna línea recta horizontal que indica la probabilidad constante para cada valor.

In [55]:
#GENERAR UN ALEATORIO ENTRE 2 NÚMEROS QUE SEAN MÚLTIPLOS DE "N"
random.randrange(20,90,4)

#límite inferior = 20
#límite superior = 89
# múltiplo (N)   = 4

68

In [56]:
#ELECCIÓN DE CARACTER ALEATORIO
CADENA = "PYTHON-2021"
random.choice(CADENA)

'O'

## PARTE 2.9: ALEATORIOS CON NUMPY

In [57]:
import numpy as np

In [79]:
#GENERAR UN ALEATORIO DECIMAL ENTRE 0-1

aleatorios_3 = np.random.random()
aleatorios_4 = np.random.random(2)
aleatorios_5 = np.random.random(3)
aleatorios_6 = np.random.random(4)
aleatorios_7 = np.random.random(5)

print(aleatorios_3)#Si no es pecifica la cantidad de elemntos que se desean, solo devolverá uno
print()

print(aleatorios_4)#Devuelve un array de dos números aleatorios
print()

print(aleatorios_5)#Devuelve un array de tres números aleatorios
print()

print(aleatorios_6)#Devuelve un array de 4 números aleatorios
print()

print(aleatorios_7.tolist())#Devuelvo el array en forma de lista para ver los elementos
                            #separados por coma","
print(aleatorios_7[1])#Me devuelve el elemento generado en la posición 1 del array

0.43505106195944476

[0.03160657 0.47750176]

[0.18729607 0.83467229 0.96111605]

[0.94961604 0.99528786 0.06033162 0.55948959]

[0.8141045674801386, 0.5314967193394382, 0.25802690131953065, 0.39688379399704987, 0.5710293649455865]
0.5314967193394382


In [83]:
#GENERAR UN ALEATORIO ENTERO ENTRE 2 NÚMEROS
#la ufunción np.random.randint() puede resivir desde un parámtro hasta 3 donde:


print(np.random.randint(20))
#Límite inferior = 0
#Límite superior = 19 #Este esá abierto por la derecha(no considera al 20)
print()
print(np.random.randint(20,30))
#Límite inferior = 20
#Límite superior = 29 #Este esá abierto por la derecha(no considera al 30)
print()

print(np.random.randint(20,30,5))
#Límite inferior = 20
#Límite superior = 29 #Este esá abierto por la derecha(no considera al 30)
#Cantidad de elementos a generar (N) = 5


10

23

[22 28 27 28 23]


In [142]:
#DEFINICIÓN DE LA SEMILLA EN LA GENERACIÓN DE NÚMEROS ALEATORIOS
# Generar un número entero al azar entre 20 y 80
aleatorios_8 = np.random.randint (20, 80,5)
print (aleatorios_8)
print()
# Establecer la semilla con el número generado
np.random.seed (aleatorios_8)

# Generar algunos números aleatorios con la misma semilla
print(np.random.random((2,3)))#Aquí le pasamos los argumentos en forma de tupla
print()                      #Genera números decimales entre 0 y 1 en un array
                            #de dos filas por tres columnas

print (np.random.rand (2,3))#Aquí no es necesario pasar los argumentos en forma de tupla
print()                     #Genera números decimales entre 0 y 1 en un array
                            #de dos filas por tres columnas


print (np.random.randint (10, 20, 5))#Genera números enteros de la siguiente manera:
#Límite inferior = 10
#Límite superior = 19 #Este esá abierto por la derecha(no considera al 20)
#Cantidad de elementos a generar (N) = 5


[43 51 54 74 53]

[[0.70370129 0.72044781 0.48641559]
 [0.62217618 0.35785162 0.81237488]]

[[0.90920137 0.5021091  0.20430394]
 [0.82895544 0.98260315 0.78658257]]

[11 12 16 15 13]
